FROM nvidia/cuda:13.0.2-cudnn-runtime-ubuntu24.04

RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --break-system-packages --no-cache-dir torch --index-url https://download.pytorch.org/whl/cu130

COPY requirements_model.txt .

RUN pip install --break-system-packages --no-cache-dir -r requirements_model.txt

COPY docker_services/model_service .
